abajstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from decouple import config

debug_mode = config('DEBUG', default=False, cast=bool)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', include('orders.urls')),
    # path('payment/', include('payment.urls')),

]
if debug_mode:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from .views import (UserRegisterView, UserLoginView, ForgetPasswordView, VerifyView, ResendOTPView, UserProfileView,
                    AddressListView, AddressDetailView, AddressCreateView, AddressUpdateView, AddressDeleteView)

app_name = "auth"

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name="register"),
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('forget-password/', ForgetPasswordView.as_view(), name='forget_password'),

    path('verify/', VerifyView.as_view(), name='verify'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend_otp'),

    path('profile/', UserProfileView.as_view(), name='profile'),

    path('addresses/', AddressListView.as_view(), name='address_list'),
    path('address/<int:pk>/', AddressDetailView.as_view(), name='address_detail'),
    path('address/new/', AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/edit/', AddressUpdateView.as_view(), name='address_update'),
    path('address/<int:pk>/delete/', AddressDeleteView.as_view(), name='address_delete'),
]

carts/urls.py
from django.urls import path
from .views import CartItemCreateUpdateView, UpdateCartItemQuantityView, CartDeleteView, CartList

app_name = 'carts'
urlpatterns = [
    path('', CartItemCreateUpdateView.as_view(), name='add'),

    path('update/', UpdateCartItemQuantityView.as_view(), name='update_cartitem'),

    path('delete/<int:pk>/', CartDeleteView.as_view(), name='remove'),
    path('my-carts/', CartList.as_view(), name='all'),

]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'
urlpatterns = [
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/checkout/', CheckoutView.as_view(), name='checkout'),

    path('orders/<int:order_id>/pay-at-home/', PayAtHomeView.as_view(), name='pay_at_home'),
    path('orders/<int:order_id>/pay/', PayOrderView.as_view(), name='pay_order'),
    path('orders/<int:order_id>/pay/mellat/', MellatPayOrderView.as_view(), name='mellat_pay_order'),
    path('orders/callback/', PaymentCallbackView.as_view(), name='pay_call_back'),
    path('orders/callback/mellat/', MellatPaymentCallbackView.as_view(), name='mellat_pay_call_back'),
    path('orders/<int:order_id>/result/', PayOrderResultView.as_view(), name='pay_result'),
    path('api/invoices/', InvoiceViewSet.as_view({'get': 'list', 'post': 'create'}), name='invoice-list'),
    path('api/invoices/<int:pk>/', InvoiceViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='invoice-detail'),
    path('api/invoices/unprinted/', InvoiceViewSet.as_view({'get': 'unprinted'}), name='invoice-unprinted'),
    path('<int:order_id>/', GetOrderLocation.as_view(), name='order_location'),
]

accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
from utils.validators import *


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_('نام'), max_length=50, null=True, blank=True, validators=[persian_characters, ])
    last_name = models.CharField(_('نام خوانوادگی'), max_length=50, null=True, blank=True, validators=[persian_characters, ])
    phone_number = models.CharField(_('شماره موبایل'), max_length=11, unique=True,
                                    validators=[persian_phone_number_validation, ])

    card_number = models.CharField(_('شماره کارت'), max_length=16, null=True, blank=True)
    shaba_number = models.CharField(_('شماره شبا'), max_length=30, null=True, blank=True)

    is_staff = models.BooleanField(_('ادمین'), default=False)
    is_superuser = models.BooleanField(_('ادمین اصلی'), default=False)
    is_verified = models.BooleanField(_('تایید شده'), default=False)

    created = models.DateField(_("تاریخ ثبتنام"), auto_now_add=True)
    updated = models.DateField(_("تاریخ آپدیت"), auto_now=True)

    USERNAME_FIELD = 'phone_number'

    objects = UserManager()

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربران'

    def __str__(self):
        return f'User ID: {self.id} - {self.phone_number}'

    @property
    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'


class OTP(models.Model):
    """
    One Time Password is for register and forget password.
    """
    phone_number = models.CharField(_('شماره موبایل'), max_length=11,
                                    validators=[persian_phone_number_validation, ])
    code = models.PositiveIntegerField(_('کد یکبارمصرف'))
    created = models.DateField(_('تاریخ تولید'), auto_now_add=True)

    class Meta:
        verbose_name = _('کد یکبارمصرف')
        verbose_name_plural = _('کد یکبارمصرف')

    def __str__(self):
        return f"{self.phone_number} - {self.code}"


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='address')
    receiver_name = models.CharField(_('نام گیرنده'), max_length=50, validators=[persian_characters, ])
    phone_number = models.CharField(_('شماره موبایل گیرنده'), max_length=11,
                                    validators=[persian_phone_number_validation, ])
    state = models.CharField(_('استان'), default='یزد', max_length=30)
    city = models.CharField(_('شهر'), max_length=30, default='یزد')
    postalcode = models.CharField(_('کد پستی'), null=True, blank=True, max_length=20, validators=[only_number, ])
    address = models.TextField(_('آدرس'))
    location = models.JSONField(null=True, blank=True)
    note = models.TextField(_('یادداشت'), blank=True, null=True)
    active = models.BooleanField(_('فعال'), default=True)
    created = models.DateField(_('تاریخ ایجاد'), auto_now_add=True)

    class Meta:
        verbose_name = _('آدرس ها')
        verbose_name_plural = _('آدرس ها')
        ordering = ('-created', )

    def __str__(self):
        return f'{self.city} - {self.address[:25]}..'

    def receiver_info(self):
        return f'{self.receiver_name}\n {self.phone_number}'

    def get_full_address(self):
        return f'{self.city} - {self.address} - {self.postalcode if self.postalcode is not None else ""}'

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic import FormView, CreateView, RedirectView, UpdateView, DeleteView, DetailView, ListView, \
    TemplateView, View
from .forms import UserCreationForm, OTPForm, ForgetPasswordForm, UserProfileForm, AddressForm, \
    CustomAuthenticationForm, ChangePasswordForm
from .models import User, OTP, Address
from .mixins import AddressFormMixin
from configs.sms_panel import send_sms
from datetime import datetime, timedelta
import random
import time
# import logging

# logging.basicConfig(filename='account_view.log',
#                     level=logging.DEBUG,
#                     format='%(asctime)s - %(levelname)s - %(message)s')


# =====================================================================================================
# ======================================== UseFull Functions ==========================================
def generate_random_password(length=8):
    password = ''.join(random.choices('0123456789', k=length))
    return password


def generate_otp(phone_number):
    random_number = random.randint(10 ** 4, 10 ** 7)
    timestamp = int(time.time() * 1000)
    code = str(timestamp + random_number)[-6:]
    OTP.objects.update_or_create(phone_number=phone_number, defaults={'code': int(code)})
    return int(code)


def send_otp(phone_number, reason):
    code = generate_otp(phone_number)

    if reason == 'register':
        pattern = '7928a99a-41b4-4e6a-a0bf-1ab47dbcaa30'
        key = {
            'token1': code,
        }
        send_sms(pattern, phone_number, key)

    if reason == 'set_new_password':
        pattern = 'da1885d9-bb31-4f8e-9bfd-0ebabb490514'
        key = {
            'token1': code,
        }
        send_sms(pattern, phone_number, key)

    if reason == 'set_new_phone_number':
        pattern = 'fb3b6bdb-a5e5-40f1-9edc-f04e0a63ef68'
        key = {
            'token1': code,
        }
        send_sms(pattern, phone_number, key)


def create_or_update_user(request):
    """ This Method Calls After Confirmation """
    if 'user_info' in request.session:
        session = request.session['user_info']
        reason = session['reason']
        phone_number = session['phone_number']

        user, created = User.objects.get_or_create(phone_number=phone_number)

        # ============================================================
        # =================== Login After Register ===================

        if reason == 'register':
            password = session['password']

            user.set_password(password)
            user.is_verified = True
            user.save()
            auth = authenticate(request, phone_number=phone_number, password=password)

            if auth is not None:
                del session
                login(request, auth)
                return 'تبریک ! حساب شما با موفقیت ایجاد شد.'
                # messages.warning(request, 'تبریک ! حساب شما با موفقیت ایجاد شد.')
                # return redirect('panel:home')

    # ============================================================
    # ======================= Update User ========================

        if reason == 'set_new_password':
            new_password = generate_random_password()
            user.set_password(new_password)
            try:
                # ==================== send sms ==========================
                pattern = 'b30f2c41-e2d1-4bcb-a26b-0d6aeb8d3ffb'
                key = {
                    'token1': new_password,
                }
                send_sms(pattern, phone_number, key)
                # =========================================================
            except Exception as e:
                print('error for sending sms : ', e)

        if reason == 'set_new_phone_number':
            new_phone_number = session['phone_number']
            user.phone_number = new_phone_number

        user.save()
        del session
        return 'عملیات با موفقت انجام  شد.'


def check_delay(request):
    now = datetime.now()

    if 'delay' in request.session:
        str_time = request.session['delay']['time']
        last_try = datetime.strptime(str_time, '%Y-%m-%d %H:%M:%S')
    else:
        last_try = now

    if last_try <= now:
        delay = now + timedelta(minutes=2)
        request.session['delay'] = {
            'time': delay.strftime('%Y-%m-%d %H:%M:%S'),
        }
        return True

    time_left = last_try - now
    total_seconds = int(time_left.total_seconds())
    request.session['total_seconds'] = total_seconds
    return False, total_seconds


def check_delay_and_send_otp(request):
    session = request.session

    if 'user_info' in session:
        user_info = session['user_info']
        phone_number = user_info['phone_number']
        reason = user_info['reason']

        delay = check_delay(request)
        if delay is True:
            try:
                send_otp(phone_number, reason)
                return 'کد یکبارمصرف برای شما ارسال شد.'
                # messages.warning(request, 'کد یکبارمصرف برای شما ارسال شد.')
                # return redirect('panel:home')

            except Exception as e:
                print('error for sending sms : ', str(e))

                return 'خطای ارسال پیامک!'
                # messages.warning(request, '!خطای ارسال پیامک')
                # return redirect('panel:home')

        return f"{delay[1]} ثانیه صبر کنید.. "
        # messages.warning(request, f"{delay[1]} ثانیه صبر کنید.. ")
        # return redirect('panel:home')
# =====================================================================================================
# =====================================================================================================


class UserRegisterView(SuccessMessageMixin, FormView):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    success_message = "کد یکبار مصرف ارسال شد!"
    success_url = reverse_lazy('auth:verify')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, 'شما از قبل وارد شده اید..')
            return redirect('products:home')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            cd = form.cleaned_data
            phone_number = cd['phone_number']
            password = cd['password']

            self.request.session['user_info'] = {
                'phone_number': phone_number,
                'password': password,
                'reason': 'register',
                }

            result = check_delay_and_send_otp(self.request)
            messages.success(self.request, result)

        messages.success(self.request, form.errors)
        return super().form_valid(form)


class UserLoginView(SuccessMessageMixin, LoginView):
    """
    Login and send success message.
    """
    form_class = CustomAuthenticationForm
    template_name = 'accounts/login.html'
    success_message = "با موفقیت وارد شدید !"
    next_page = reverse_lazy('products:home')


from django.shortcuts import get_object_or_404

class VerifyView(FormView):
    form_class = OTPForm
    template_name = 'accounts/otp.html'
    success_url = reverse_lazy('products:home')

    def form_valid(self, form):
        session = self.request.session.get('user_info')

        if form.is_valid() and session:
            cd = form.cleaned_data
            user_entered_code = cd['code']

            try:
                otp = OTP.objects.get(phone_number=session['phone_number'], code=user_entered_code)
            except OTP.DoesNotExist:
                messages.error(self.request, 'کد وارد شده صحیح نمی‌باشد ❌')
                return self.form_invalid(form)  # جلوگیری از ادامه روند

            # حذف OTP فقط بعد از تأیید کامل
            otp.delete()

            # ساخت یا به‌روزرسانی کاربر
            result = create_or_update_user(self.request)
            messages.success(self.request, result)

            return redirect('products:home')

        messages.info(self.request, 'کد وارد شده صحیح نمیباشد')
        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session = self.request.session
        if session:
            if 'user_info' in session:
                context['user_phone_number'] = session['user_info']['phone_number']
            context['total_seconds'] = session.get('total_seconds', 120)
        return context


  


class ForgetPasswordView(FormView):
    form_class = ForgetPasswordForm
    template_name = 'accounts/forget_password.html'
    success_url = reverse_lazy('auth:verify')

    def form_valid(self, form):
        if form.is_valid():
            cd = form.cleaned_data
            phone_number = cd['phone_number']

            self.request.session['user_info'] = {
                'phone_number': phone_number,
                'reason': 'set_new_password'
            }

            result = check_delay_and_send_otp(self.request)
            messages.info(self.request, result)

        return super().form_valid(form)


class ResendOTPView(RedirectView):
    pattern_name = 'auth:verify'

    def get(self, request, *args, **kwargs):
        result = check_delay_and_send_otp(request)
        messages.info(request, result)

        return super().get(request, *args, **kwargs)


class UserProfileView(LoginRequiredMixin, TemplateView):
    model = User
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('auth:profile')
    context_object_name = 'profile'

templates/accounts/forget_password.html
{% extends 'accounts_base.html' %}
{% load static %}


{% block title %}
    فراموشی رمز
{% endblock %}



{% block form %}
      <section>
        <div class="flex flex-col gap-10">
          <h1 class="text-xl text-lowGray">شماره موبایل خود را وارد کنید</h1>
          <div>
            <label for="input" class="text-sm text-lowGray">
            </label>
          </div>
          <form method="post">
                  {% csrf_token %}
                  {{ form.phone_number }}
                  {{ form.phone_number.errors }}

              <button type="submit"
                class="bg-redColor opacity-80 hover:opacity-100 transition-opacity duration-300 text-whiteColor py-3 w-full rounded-md"
              >
                ارسال کد
            </button>
          </form>
        </div>
      </section>

{% endblock %}



{% block scripts %}

{% endblock %}

templates/accounts/login.html
{% extends 'accounts_base.html' %}
{% load static %}


    {% block title %} ورود {% endblock %}

          {% block form %}

      <section>
        <form method="post" class="flex flex-col gap-5">
            {% csrf_token %}
          <h1 class="text-xl text-lowGray">ورود</h1>
          <div>
            <label for="userName" class="text-sm text-lowGray">
               شماره موبایل خود را وارد کنید
            </label>
              {{ form.username }}
              {{ form.username.errors }}
          </div>
          <div>
            <label for="userPass" class="text-sm text-lowGray">
               رمز خود را وارد کنید
            </label>
              {{ form.password }}
              {{ form.password.errors }}
          </div>
              {{ form.non_field_errors }}
          <button type="submit"
            class="bg-redColor opacity-80 hover:opacity-100 transition-opacity duration-300 text-whiteColor py-3 w-full rounded-md"
          >
            ورود
          </button>
        </form>
      </section>
      <section>
        <p class="text-[14px] text-center">
           حساب ندارید؟
          <a href="{% url 'auth:register' %}" class="text-linkColor"> از اینجا وارد شوید </a>
        </p>
          <p class="text-[14px] text-center">
          <a href="{% url 'auth:forget_password' %}" class="text-linkColor"> رمز عبور خود را فراموش کرده ام </a>
        </p>
      </section>
    {% endblock %}

templates/accounts/my-addresses.html
{% extends 'base.html' %}
{% load static %}



{% block title %} آدرس های من {% endblock %}


{% block style %} 
    <link href="{% static 'styles/nouislider.css' %}" rel="stylesheet" />
    <script src="{% static 'scripts/nouislider.js' %}"></script>

{% endblock %}





{% block content %} 
    
    
    
    <main class="lg:pt-[120px]">
    
      <section
        id="hiddenContent"
        class="bg-lowOpacityColorBg items-start hidden fixed z-[9] top-0 right-0 w-full h-screen"
      ></section>
      <section
        id="hiddenContent"
        class="bg-lowOpacityColorBg items-start hidden fixed z-[9] top-0 right-0 w-full h-screen"
      ></section>
      <section>
        <div
          class="container flex lg:flex-row justify-between items-start flex-col p-2 gap-5"
        ><aside
            class="min-w-[338px] lg:block hidden sticky top-[120px] boxBorder rounded-md py-2 px-4"
          >
            <nav>
              <ul class="space-y-3">
                <li class="flex flex-col gap-4 px-4">
                  <div class="flex items-center gap-4">
                    <img
                      src="https://www.zagros.market/themes/shop-theme1/images/avatar.svg"
                      alt="پروفایل"
                      class="w-[44px]"
                    />
                    <p>{{ request.user.phone_number }}</p>
                  </div>
                  <span class="w-full boxBorder"></span>
                </li>
                <li>
                  <a
                    href="{% url 'orders:order_list' %}"
                    class="flex items-center transition-[background] gap-4 w-full py-4 hover:bg-submitPageColorBorderLowBlack px-4 text-sm"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      class="size-6"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184"
                      />
                    </svg>
                    <span class="text-lowGray">سفارشات</span>
                  </a>
                </li>
                <li class="selectedBeforBorderRight">
                  <a
                    href="{% url 'auth:address_list' %}"
                    class="flex items-center transition-[background] gap-4 w-full py-4 hover:bg-submitPageColorBorderLowBlack px-4 text-sm"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      class="size-6"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
                      />
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z"
                      />
                    </svg>

                    <span class="text-blackColor font-bold">آدرس ها</span>
                  </a>
                </li>
                <li>
                  <a
                    href="{% url 'auth:profile' %}"
                    class="flex items-center transition-[background] gap-4 w-full py-4 hover:bg-submitPageColorBorderLowBlack px-4 text-sm"
                  >
                    <i class="far fa-user text-2xl"></i>
                    <span class="text-lowGray"
                      >اطلاعات حساب کاربری</span
                    >
                  </a>
                </li>
                <li>
                    <form method="post"  action="{% url 'auth:logout' %}">
                        {% csrf_token %}
                  <button
                          type="submit"
                    class="flex items-center transition-[background] gap-4 w-full py-4 hover:bg-submitPageColorBorderLowBlack px-4 text-sm"
                  >
                    <i class="fa fa-sign-out text-2xl"></i>
                    <span class="text-lowGray">خروج</span>
                  </button>
                    </form>
                    
                </li>
              </ul>
            </nav>
          </aside>
        
        
        
{% if not addresses %}
    
      <div class="sm:text-lg text-sm divTextAlert danger">
        <p>لیست آدرس های شما خالی است!</p>
      </div>
    
{% else %}
    
          <div class="w-full space-y-5 lg:boxBorder rounded-md p-3">
            <h2 class="lg:flex hidden flex-col gap-2 py-4">
              <span>آدرس های من</span>
              <span class="w-[50px] bg-primary h-[2px]"></span>
            </h2>
            <ul>
            
                {% for address in addresses %}
              <li
                class="space-y-4 p-4 rounded-md border border-submitPageColorBorderLowBlack"
              >
                <div class="text-lowGray space-y-2">
                  <p class="text-blackColor">
                    {{ address.address }}
                  </p>
                  <p>
                    <i class="far fa-user"></i>
                    <span>{{ address.receiver_name }}</span>
                  </p>
                  <p>
                    <i class="far fa-phone"></i>
                    <span>{{ address.phone_number }}</span>
                  </p>
                </div>
            <form class="text-lg flex gap-2" method="post" action="{% url 'auth:address_delete' address.id %}"> 
              {% csrf_token %}
            
                  <button
                    type="submit"
                    class="cursor-pointer border-primary border rounded-md py-1 px-3 text-primary"
                  >
                    <i class="fa fa-pencil"></i>
                    <span>حذف</span>
                  </button>
                </form>
              </li>
                {% endfor %}
            </ul>
          </div>
{% endif %}
          <div class="lg:block hidden"></div>
        </div>
      </section>
    </main>

  
  
  
    
    
    
    
{% endblock %}





{% block scripts %} 

    <script>
      let addUs_birthday = document.querySelector("#user_birthday");
      jalaliDatepicker.startWatch({
        dayRendering: function (dayOptions, addUs_birthday) {
          return {
            isHollyDay: dayOptions.month == 1 && dayOptions.day <= 4,
          };
        },
      });
    </script>
{% endblock %}


    

templates/accounts/otp.html
{% extends 'accounts_base.html' %}
{% load static %}


{% block title %}
    تایید کد
{% endblock %}



{% block form %}
      <section>
        <div class="flex flex-col gap-10">
          <h1 class="text-xl text-lowGray">کد تایید را وارد کنید</h1>
          <div>
            <label for="input" class="text-sm text-lowGray">
              کد تایید به شماره <span>{{ user_phone_number }}</span> پیامک شد
            </label>
          </div>
          <form method="post">
                  {% csrf_token %}
                  {{ form.code }}
                  {{ form.code.errors }}
              <a class="text-center text-sm">
                ارسال مجدد کد تا
                <span id="timer"></span>
                دیگر
              </a>
                  </br></br>
                  
              <button type="submit"
                class="bg-redColor opacity-80 hover:opacity-100 transition-opacity duration-300 text-whiteColor py-3 w-full rounded-md"
              >
                ورود
            </button>
          </form>
        </div>
      </section>

{% endblock %}



{% block scripts %}
    <script>
      const timerLink = document.querySelector("#timer");

      let sec = {{ total_seconds }};
      let linkHref = "{% url 'auth:resend_otp' %}";
      function timer() {
        if (sec <= 0) {
          timerLink.parentElement.href = linkHref;
          timerLink.parentElement.textContent = "دریافت مجدد کد تایید";
          clearInterval(interval);
          return;
        }
        sec--;

        timerLink.textContent = sec;
      }
      interval = setInterval(() => timer(), 1000);
      timer();
    </script>
{% endblock %}

templates/accounts/register.html
{% extends 'accounts_base.html' %}
{% load static %}


    {% block title %} ثبت نام {% endblock %}

          {% block form %}

      <section>
        <form class="flex flex-col gap-5" method="post">
            {% csrf_token %}
          <h1 class="text-xl text-lowGray">ثبت ‌نام</h1>
          <div>
            <label for="userName" class="text-sm text-lowGray">
              لطفا شماره موبایل خود را وارد کنید
            </label>
              {{ form.phone_number }}
              {{ form.phone_number.errors }}
              {{ form.non_field_errors }}
          </div>
          <div>
            <label for="userPass" class="text-sm text-lowGray">
              لطفا رمز خود را وارد کنید
            </label>
              {{ form.password }}
              {{ form.password.errors }}
          </div>
          <button type="submit"
            class="bg-redColor opacity-80 hover:opacity-100 transition-opacity duration-300 text-whiteColor py-3 w-full rounded-md"
          >
            ثبت نام
          </button>
        </form>
      </section>
      <section>
        <p class="text-[14px] text-center">
           حساب دارید؟
          <a href="{% url 'auth:login' %}" class="text-linkColor"> از اینجا وارد شوید </a>
        </p>
      </section>
    {% endblock %}