abajstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from decouple import config

debug_mode = config('DEBUG', default=False, cast=bool)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', include('orders.urls')),
    # path('payment/', include('payment.urls')),

]
if debug_mode:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import CartItemCreateUpdateView, UpdateCartItemQuantityView, CartDeleteView, CartList

app_name = 'carts'
urlpatterns = [
    path('', CartItemCreateUpdateView.as_view(), name='add'),

    path('update/', UpdateCartItemQuantityView.as_view(), name='update_cartitem'),

    path('delete/<int:pk>/', CartDeleteView.as_view(), name='remove'),
    path('my-carts/', CartList.as_view(), name='all'),

]

products/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from .views import HomeView, ProductListView, ProductDetailView

app_name = "products"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

products/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext as _
from .managers import AvailableManager


class Base(models.Model):
    name = models.CharField(_('نام'), max_length=40, unique=True)
    image = models.ImageField(_('عکس'), upload_to='category-and-brands/', null=True, blank=True)

    def __str__(self):
        return self.name


class Brand(Base):
    class Meta:
        verbose_name = "برند"
        verbose_name_plural = "برند ها"


class MainCategory(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(_('نام'), max_length=40, db_index=True)
    image = models.ImageField(_('عکس'), upload_to='category-and-brands/', null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, verbose_name='زیر دسته',
                               related_name='children')

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی"

    def __str__(self):
        return self.name


class SpecialCategory(Base):
    class Meta:
        verbose_name = "دسته بندی مناسبتی"
        verbose_name_plural = "دسته بندی مناسبتی"


class ProductFeature(models.Model):
    product = models.ForeignKey('Product', related_name='features', on_delete=models.PROTECT, verbose_name='محصول')
    key = models.CharField(_('موضوع'), max_length=100)
    value = models.CharField(_('مقدار'), max_length=100)

    def __str__(self):
        return f"{self.key}: {self.value}"


class Product(models.Model):
    code = models.CharField(_('کد محصول'), max_length=15, null=True, blank=True, unique=True, db_index=True)
    cover_image = models.ImageField(_('عکس کاور'), upload_to='cover_images/', null=True, blank=True)
    name = models.CharField(_('نام محصول'), max_length=200, db_index=True)

    brand = models.ForeignKey(Brand, related_name='products', on_delete=models.SET_NULL,
                              null=True, blank=True, verbose_name='برند')

    category = models.ForeignKey(MainCategory, related_name='products', on_delete=models.SET_NULL,
                                 null=True, blank=True, verbose_name='دسته بندی اصلی')
    price = models.DecimalField(_('قیمت'), max_digits=12, decimal_places=3)
    discount = models.PositiveSmallIntegerField(_('تخفیف (%)'), default=0, validators=(MinValueValidator(0),))
    unit_type = models.PositiveSmallIntegerField(_('واحد'), default=1, choices=[(1, 'عدد'), (2, 'کیلو')])
    quantity = models.DecimalField(_('تعداد'), default=1.0, max_digits=12, decimal_places=3)
    description = models.TextField(_('توضیحات'), null=True, blank=True)
    active = models.BooleanField(_('فعال'), default=True)
    objects = models.Manager()
    available = AvailableManager()

    created = models.DateField(_('تاریخ ایجاد'), auto_now_add=True)
    updated = models.DateField(_('تاریخ آپدیت'), auto_now=True)

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return f'{self.name[:15]}... - کد: {self.code}'

    @property
    def discounted_price(self):
        if self.discount:
            return int(self.price * (1 - (self.discount / 100)))
        return self.price

products/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
import django_filters
from django_filters.views import FilterView
from carts.models import Cart
from .models import Product, MainCategory
from carts.forms import CartItemForm
from configs.sepandyar_webAPI import get_product

# class ProductFilter(django_filters.FilterSet):
#     class Meta:
#         model = Product
#         fields = {
#             'name': ['exact', 'icontains'],
#             'brand': ['exact', 'icontains'],
#             'category': ['exact'],
#             'colors': ['exact'],
#             'price': ['gte', 'lte'],
#             'discount': ['gte', 'lte'],
#             'avg_rate': ['gte', 'lte'],
#             'created': ['gte', 'lte'],
#         }


# /products/?name=product1&brand__icontains=brand1&price__gte=1000&price__lte=5000&ordering=price


class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(field_name='name', lookup_expr='contains')
    brand = django_filters.CharFilter(field_name='brand', lookup_expr='contains')
    # category = django_filters.ModelMultipleChoiceFilter(queryset=MainCategory.objects.all())
    category = django_filters.CharFilter(method='filter_by_category_name_or_parent')
    price_min = django_filters.NumberFilter(field_name='price', lookup_expr='gte', label='حداقل قیمت')
    price_max = django_filters.NumberFilter(field_name='price', lookup_expr='lte', label='حداکثر قیمت')

    order_by = django_filters.OrderingFilter(
        fields=(
            ('created', 'created'),
            ('price', 'price'),
            ('discount', 'discount'),
            # ('avg_rate', 'avg_rate'),
        )
    )

    class Meta:
        model = Product
        fields = ['name', 'brand', 'category', 'price_min', 'price_max']

    def filter_by_category_name_or_parent(self, queryset, name, value):
        return queryset.filter(
            Q(category__name__iexact=value) | Q(category__parent__name__iexact=value)
        )


class HomeView(TemplateView):
    template_name = 'products/home.html'

    def get(self, request, *args, **kwargs):
        # messages.warning(request, 'سایت در مرحله تست و ارزیابی می باشد ، لطفا از خرید و ثبت سفارش خودداری فرمایید.')
        return super().get(request, *args, **kwargs)


class ProductListView(FilterView):
    model = Product
    template_name = 'products/all-products.html'
    context_object_name = 'products'
    paginate_by = 20
    filterset_class = ProductFilter

    def get_queryset(self):
        return Product.available.all().order_by('-id')

    def get_queryset(self):
        queryset = Product.available.all().order_by('-created')
        filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['filter'] = self.filterset_class(self.request.GET, queryset=self.get_queryset())
        parent_category = self.request.GET.get('category')
        if parent_category:
            sub_category = MainCategory.objects.filter(parent__name=parent_category)
            context['suggest_categories'] = sub_category
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'products/product-detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # cart, _ = Cart.objects.get_or_create(user=self.request.user)
        # for cart_item in cart.cart_items.all():
        #     if cart_item.product.id == self.get_object().id:
        #         context['cart_item'] = cart_item
        #     else:
        #         context['cart_item'] = None

        context['form'] = CartItemForm()
        # try:
        #     context['quantity'] = int(get_product(self.get_object().code)['Quantity'])
        # except Exception as e:
        #     print(str(e))
        #     context['quantity'] = 1
        return context

templates/products/product-detail.html
{% extends 'base.html' %}
{% load static %}



{% block title %} جزئیات محصول {% endblock %}

{% block style %}
    
 {% endblock %}





{% block content %} 
    
    
    
    
    
    <main class="lg:pt-[130px]">
      <section
        id="hiddenContent"
        class="bg-lowOpacityColorBg items-start hidden fixed z-[9] top-0 right-0 w-full h-screen"
      ></section>
      <section>
        <div
          class="container flex gap-2 text-lowGray text-[12px] text-nowrap overflow-auto"
        >
          <a href="{% url 'products:home' %}">صفحه اصلی</a>
        
            {% if product.category.parent %}
          <span class="cursor-default select-none">/</span>
          <a href="{% url 'products:product_list' %}?category={{ product.category.parent.name }}">
              {{ product.category.parent.name }}</a>
            {% endif %}
        
            {% if product.category %}
          <span class="cursor-default select-none">/</span>
          <a href="{% url 'products:product_list' %}?category={{ product.category.name }}">
              {{ product.category.name }}</a>
            {% endif %}
        
          <span class="cursor-default select-none">/</span>
          <p>{{ product.name }}</p>
        </div>
      </section>
      <section>
        <div class="container flex lg:flex-row flex-col gap-4">
          <div class="lg:basis-[25%] w-full relative">
            <img
              class="w-full"
              src="{% if product.cover_image %}
                            {{ product.cover_image.url }}
                            {% else %}
                            {% static 'assets/images/default-image2.jpg' %}
                            {% endif %}"
              alt="{{ product.name }}"
            />
            <button
              id="imagesShowCont"
              class="p-2 absolute text-lowGray text-xl top-0 lg:right-0 max-w-max left-4"
            >
              <i class="fa fa-search"></i>
            </button>
            <div
              id="imagesShow"
              class="sm:bg-lowOpacityColorBg hidden py-2 backdrop-filter-[blur(50px)] transition-all bg-blackColor fixed top-0 left-0 w-full h-full items-center justify-center z-[100]"
            >
              <img
                src="{% if product.cover_image %}
                            {{ product.cover_image.url }}
                            {% else %}
                            {% static 'assets/images/default-image2.jpg' %}
                            {% endif %}"
                alt="{{ product.name }}"
                class="w-full object-contain max-h-[700px] h-[95%]"
              />
              <button
                class="absolute sm:bg-[transparent] bg-lowOpacityColorBg text-whiteColor left-[20px] text-2xl top-[10px] px-2 py-1 bg-red"
              >
                <i class="fa fa-remove"></i>
              </button>
            </div>
          </div>
          <div class="lg:basis-[75%] w-full">
            <h1 class="py-2 border-b border-submitPageColorBorderLowBlack">
              {{ product.name }}
            </h1>
            <div class="space-y-2 text-sm py-4">
              <div class="flex gap-4">
                <p>
                  <i class="fa fa-barcode"></i> کد محصول : <span> {{ product.code }} </span>
                </p>
              
{#                <p>#}
{#                    {% if quantity == 0 %}#}
{#                        <i class="fa fa-home"></i>#}
{#                        <span> #}
{#                            کالا در انبار موجود نیست#}
{#                        </span>#}
{#                    {% else %}#}
{#                        <i class="fa fa-home"></i> موجودی انبار : #}
{#                        <span> #}
{#                        {{ quantity }}#}
{#                        </span>#}
{#                    {% endif %}#}
{#                </p>#}
              {% if product.category %}
                <p>
                  <i class="far fa-folder-open"></i> دسته بندی : 
                  <a href="#" class="text-lowGray hover:text-blackColor"> {{ product.category.name }} </a>
                </p>
              {% endif %}
              </div>

                <p class="priceProduct text-lg" id="productPrice">
                  <span class="setFormatNumber">{{ product.discounted_price }}</span>
                <span> تومان </span>
              </p>

                <div>
            
            {% if product.unit_type == 1 %}
                    
                      <form method="post" action="{% url 'carts:add' %}" class="flex gap-2 flex-col">
                          {% csrf_token %}
                        <input type="hidden" name="product" value="{{ product.id }}">
{#                        <input type="hidden" name="quantity" value="1.0">#}
                        <div
                          id="pcsProduct"
                          class="flex justify-between p-2 max-w-[200px] w-full rounded-lg gap-2 boxBorder"
                        >
                          <button type="button">
                            <i class="text-lg fa fa-plus"></i>
                          </button>
                            {{ form.quantity }}
                            {{ form.quantity.errors }}
                            <p>عدد</p>
                          <button type="button">
                            <i class="text-lg fa fa-minus"></i>
                          </button>
                        </div>
                        <button
                          type="submit"
                          class="p-2 py-2 bg-redColor max-w-[200px] w-full opacity-75 hover:opacity-100 transition-all text-[16px] text-whiteColor rounded-lg"
                        >
                          <i class="fas fa-shopping-cart"></i>
                           افزودن به سبد خرید
                        </button>
                          
                      </form>
                <p>* لطفا پس از وارد کردن تعداد دلخواه ، دکمه افزودن به سبد خرید را بزنید.</p>
                
            
            {% else %}
                    
                      <form method="post" action="{% url 'carts:add' %}" class="flex gap-2 flex-wrap">
                          {% csrf_token %}
                        <input type="hidden" name="product" value="{{ product.id }}">
{#                        <input type="hidden" name="quantity" value="1.0">#}
                        <div
                          id="pcsProduct"
                          class="flex justify-between p-2 max-w-[200px] w-full rounded-lg gap-2 boxBorder"
                        >
                          <button type="button">
                            <i class="text-lg fa fa-plus"></i>
                          </button>
                            {{ form.quantity }}
                            {{ form.quantity.errors }}
                            <p>کیلو</p>
                          <button type="button">
                            <i class="text-lg fa fa-minus"></i>
                          </button>
                        </div>
                        <button
                          type="submit"
                          class="p-2 py-2 bg-redColor max-w-[200px] w-full opacity-75 hover:opacity-100 transition-all text-[16px] text-whiteColor rounded-lg"
                        >
                          <i class="fas fa-shopping-cart"></i>
                           افزودن به سبد خرید
                        </button>
                          
                      </form>

                <p>قیمت نهایی : <span id="productPriceMathMethod" class="min-h-5">0</span></p>

                <p>* فروش این کالا به صورت فله ای میباشد
                              ، لطفا پس از وارد کردن وزن دلخواه ، دکمه افزودن به سبد خرید را بزنید.</p>
                
                {% endif %}
            
            
            
            
            
            
            
            
{#                {% if cart_item and product.unit_type == 1 %}#}
{##}
{#                          <form method="post" action="{% url 'carts:update_cartitem' %}">#}
{#                              {% csrf_token %}#}
{#                                  <input type="hidden" name="cartitem_id" value="{{ cart_item.id }}">#}
{#                            <div#}
{#                              class="flex pcsProduct bg-whiteColor justify-between p-2 max-w-[200px] w-full rounded-lg gap-2 boxBorder"#}
{#                            >#}
{#                              <button type="submit" name="action" value="increase">#}
{#                                <i class="text-lg fa fa-plus"></i>#}
{#                              </button>#}
{#                              <input#}
{#                              disabled#}
{#                                type="text"#}
{#                                class="bg-[transparent] text-center w-full outline-none"#}
{#                                name="asd"#}
{#                                value="{{ cart_item.rounded_quantity }}"#}
{#                              />#}
{#                              <button type="submit" name="action" value="decrease">#}
{#                                <i class="text-lg fa fa-minus"></i>#}
{#                              </button>#}
{#                            </div>#}
{#                            عدد#}
{#                          </form>#}
{#                            #}
{#                {% elif product.unit_type == 1 %}#}
{#                        #}
{#                              <form method="post" action="{% url 'carts:add' %}" class="flex gap-2 flex-wrap">#}
{#                                  {% csrf_token %}#}
{#                                <input type="hidden" name="product" value="{{ product.id }}">#}
{#                                <input type="hidden" name="quantity" value="1.0">#}
                {#                <div#}
                {#                  id="pcsProduct"#}
                {#                  class="flex justify-between p-2 max-w-[200px] w-full rounded-lg gap-2 boxBorder"#}
                {#                >#}
                {#                  <button type="button">#}
                {#                    <i class="text-lg fa fa-plus"></i>#}
                {#                  </button>#}
                {#                    {{ form.quantity }}#}
                {#                    {{ form.quantity.errors }}#}
                {#                  <button type="button">#}
                {#                    <i class="text-lg fa fa-minus"></i>#}
                {#                  </button>#}
                {#                </div>#}
{#                                <button#}
{#                                  type="submit"#}
{#                                  class="p-2 py-2 bg-redColor max-w-[200px] w-full opacity-75 hover:opacity-100 transition-all text-[16px] text-whiteColor rounded-lg"#}
{#                                >#}
{#                                  <i class="fas fa-shopping-cart"></i>#}
{#                                  افزودن به سبد خرید#}
{#                                </button>#}
{#                              </form>#}
{#                            #}
{#                {% endif %}#}
                    
                
                </div>
            </div>
          </div>
        </div>
      </section>
    
    {% if product.unit_type == 2 %}
                
      <section>
       <div class="container">
          <div class="boxBorder rounded-md p-4 space-y-2">
            <h3>توجه</h3>
            <p>
              برای سفارش اجناس کیلویی میتوانید ارقام را به صورت اعشاری وارد
              نمایید. مثال:
            </p>
            <p>250 گرم (ربع کیلو) به صورت: 0.250</p>
            <p>500 گرم (نیم کیلو) به صورت: 0.500</p>
            <p>یک کیلو و 250 گرم به صورت: 1.250</p>
          </div>
        </div>
      </section>
    
    {% endif %}    
    
      <section>
        <div class="container"></div>
      </section>
    </main>
    
    
    
    
    
{% endblock %}





{% block scripts %}
        <script>
      $("#imagesShowCont").on("click", () => {
        $("#imagesShow").toggleClass("showImagesShow");
      });
      $("#imagesShow ").on("click", () => {
        $("#imagesShow").removeClass("showImagesShow");
      });

      let minLength = {% if product.unit_type == 1 %}1{% else %}0.1{% endif %};
      let methodNumber = minLength;
      let maxFloat = 1;
      function methodPcsProduct(e) {
        if ($("#pcsProduct input")[0].value) {
          $("#productPriceMathMethod").text(
            Number(
              $("#pcsProduct input")[0].value *
                $("#productPrice")[0].children[0].textContent.replace(/\,/g, "")
            ).toLocaleString()
          );
        }
      }
      $("#pcsProduct input").on("input", methodPcsProduct);
      $("#pcsProduct button").on("click", function () {
        if (this.children[0].classList.contains("fa-plus")) {
        let value =
            Number($("#pcsProduct input")[0].value) + Number(methodNumber);
          if (String(value).includes(".")) value = value.toFixed(maxFloat);
          $("#pcsProduct input").val(value);
        } else if ($("#pcsProduct input")[0].value > minLength) {
          let value =
            Number($("#pcsProduct input")[0].value) - Number(methodNumber);
          if (String(value).includes(".")) value = value.toFixed(maxFloat);
          $("#pcsProduct input").val(value);
        }
        methodPcsProduct();
      });
      
    </script>
 {% endblock %}