abajstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from decouple import config

debug_mode = config('DEBUG', default=False, cast=bool)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', include('orders.urls')),
    # path('payment/', include('payment.urls')),

]
if debug_mode:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import CartItemCreateUpdateView, UpdateCartItemQuantityView, CartDeleteView, CartList

app_name = 'carts'
urlpatterns = [
    path('', CartItemCreateUpdateView.as_view(), name='add'),

    path('update/', UpdateCartItemQuantityView.as_view(), name='update_cartitem'),

    path('delete/<int:pk>/', CartDeleteView.as_view(), name='remove'),
    path('my-carts/', CartList.as_view(), name='all'),

]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'
urlpatterns = [
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/checkout/', CheckoutView.as_view(), name='checkout'),

    path('orders/<int:order_id>/pay-at-home/', PayAtHomeView.as_view(), name='pay_at_home'),
    path('orders/<int:order_id>/pay/', PayOrderView.as_view(), name='pay_order'),
    path('orders/<int:order_id>/pay/mellat/', MellatPayOrderView.as_view(), name='mellat_pay_order'),
    path('orders/callback/', PaymentCallbackView.as_view(), name='pay_call_back'),
    path('orders/callback/mellat/', MellatPaymentCallbackView.as_view(), name='mellat_pay_call_back'),
    path('orders/<int:order_id>/result/', PayOrderResultView.as_view(), name='pay_result'),
    path('api/invoices/', InvoiceViewSet.as_view({'get': 'list', 'post': 'create'}), name='invoice-list'),
    path('api/invoices/<int:pk>/', InvoiceViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='invoice-detail'),
    path('api/invoices/unprinted/', InvoiceViewSet.as_view({'get': 'unprinted'}), name='invoice-unprinted'),
    path('<int:order_id>/', GetOrderLocation.as_view(), name='order_location'),
]

products/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from .views import HomeView, ProductListView, ProductDetailView

app_name = "products"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

carts/models.py
from django.db import models
from products.models import Product
from django.utils.translation import gettext as _
from accounts.models import User


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='کاربر', related_name='cart')
    send_price = models.PositiveIntegerField(_('هزینه ی ارسال'), default=0, help_text='به تومان')

    created = models.DateField(_('تاریخ ایجاد'), auto_now_add=True)
    updated = models.DateField(_('تاریخ آپدیت'), auto_now=True)

    class Meta:
        verbose_name = "سبد خرید"
        verbose_name_plural = "سبد خرید"

    def __str__(self):
        return f'سبد برای : {self.user}'

    def calculate_total_price(self):
        return sum(cart.cart_item_price() for cart in self.cart_items.all())

    def calculate_total_discounted_price(self):
        return sum(cart.cart_item_discounted_price() for cart in self.cart_items.all()) + self.send_price

    def calculate_total_discount(self):
        return sum(cart.cart_item_discount() for cart in self.cart_items.all())

    def total_quantity(self):
        return self.cart_items.all().count()


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items", verbose_name='سبد خرید')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, verbose_name='محصول')
    quantity = models.DecimalField(_('تعداد'), default=1.0, max_digits=12, decimal_places=7)

    created = models.DateField(_('تاریخ ایجاد'), auto_now_add=True)
    updated = models.DateField(_('تاریخ آپدیت'), auto_now=True)

    class Meta:
        verbose_name = "آیتم سبد خرید"
        verbose_name_plural = "آیتم سبد خرید"

    def __str__(self):
        return f"{self.quantity} عدد از {self.product}"

    def cart_item_price(self):
        return int(self.product.price * self.quantity)

    def cart_item_discounted_price(self):
        return int(self.product.price * self.quantity)

    def cart_item_discount(self):
        return (self.product.price * self.quantity) - (self.product.discounted_price * self.quantity)

    @property
    def rounded_quantity(self):
        return int(self.quantity) if self.product.unit_type == 1 else round(self.quantity, 1)

carts/forms.py
from django import forms
from products.models import Product
from .models import CartItem


class CartItemForm(forms.ModelForm):
    quantity = forms.CharField(widget=forms.TextInput(
                                      attrs={'class': 'bg-[transparent] text-center w-full outline-none',
                                             'placeholder': '1',
                                             # 'value': '1.0'
                                             }),
                                  )

    class Meta:
        model = CartItem
        fields = ('product', 'quantity',)

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     if self.instance.pk:
    #         self.fields['quantity'].initial = self.instance.rounded_quantity

    # def validate_quantity(self, value):
    #     print(value)
    #     if int(value) > self.product.quantity:
    #         raise forms.ValidationError('تعداد بیش از حد موجودی است!')
    #     return value

carts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView, DeleteView, RedirectView
from products.models import Product
from .forms import CartItemForm
from .models import Cart, CartItem
from configs.sepandyar_webAPI import get_product
from decimal import Decimal

def get_quantity_from_api(product_code):
    try:
        get_product_from_api = get_product(product_code)

        if get_product_from_api is not None:
            product_quantity = get_product_from_api['Quantity']
            return product_quantity

        return 1

    except Exception as e:
        print(str(e))

        try:
            return Product.objects.get(code=product_code).quantity
        except Exception as e:
            print(str(e))
            return 1


class CartItemCreateUpdateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return redirect('products:home')

    def post(self, request, *args, **kwargs):
        # product_id = request.POST.get('product_id')
        # product = get_object_or_404(Product, id=product_id)

        form = CartItemForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            quantity = cd['quantity']
            product = cd['product']
            product_quantity = get_quantity_from_api(product.code)

            if product_quantity < float(quantity):
                messages.error(request, 'تعداد درخواستی از مانده انبار بیشتر می باشد!')
                return redirect(request.META.get('HTTP_REFERER', 'carts:all'))

            try:
                cart, _ = Cart.objects.get_or_create(user=self.request.user)
                cart_item, created = CartItem.objects.update_or_create(cart=cart, product=product)

                cart_item.quantity = quantity
                cart_item.save()

                messages.success(self.request, 'محصول به سبد خرید اضافه شد!')
                return redirect(request.META.get('HTTP_REFERER', 'carts:all'))

            except Exception as e:
                messages.error(self.request, 'خطا در انجام درخواست!')

        return redirect(request.META.get('HTTP_REFERER', 'carts:all'))
        # return HttpResponse("اطلاعات ارسال شده نامعتبر است!", status=400)
        # return super().post(request, *args, **kwargs)

# class CartItemCreateUpdateView(LoginRequiredMixin, CreateView):
#     model = CartItem
#     form_class = CartItemForm
#     template_name = 'cart/cart_item_form.html'
#     success_url = reverse_lazy('carts:all')
#
#     def form_valid(self, form):
#         product = form.cleaned_data['product']
#         quantity = form.cleaned_data['quantity']
#         color = form.cleaned_data['color']
#
#         if product.quantity < quantity:
#             messages.error(self.request, 'موجودی کافی نیست.')
#             return self.form_invalid(form)
#
#         try:
#             cart, created = Cart.objects.get_or_create(user=self.request.user)
#             cart_item, created = CartItem.objects.update_or_create(
#                 cart=cart,
#                 product=product,
#                 color=color,
#                 defaults={'quantity': quantity}
#             )
#             messages.success(self.request, 'سبد خرید با موفقیت به‌روز شد.')
#         except Exception as e:
#             messages.error(self.request, 'خطایی در به‌روزرسانی سبد خرید رخ داد.')
#             return self.form_invalid(form)
#
#         return super().form_valid(form)


class CartDeleteView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = kwargs.get('pk')
        cart_item = get_object_or_404(CartItem, pk=cart_id)
        cart_item.delete()

        return redirect('carts:all')

# class CartDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
#     model = CartItem
#     success_url = reverse_lazy('carts:all')
#
#     def test_func(self):
#         cart_item = self.get_object()
#         return cart_item.cart.user == self.request.user


class CartList(LoginRequiredMixin, TemplateView):
    template_name = 'carts/my-carts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart, _ = Cart.objects.get_or_create(user=self.request.user)
        context['carts'] = cart.cart_items.all()
        context['cart'] = cart
        return context

# class CartList(LoginRequiredMixin, ListView):
#     model = CartItem
#     template_name = 'cart/cart_list.html'
#     context_object_name = 'cart_items'
#
#     def get_queryset(self):
#         cart, _ = Cart.objects.get_or_create(user=self.request.user)
#         return CartItem.objects.filter(cart=cart)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['cart'] = self.request.user.cart
#         return context


class UpdateCartItemQuantityView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        cart_item_id = request.POST.get('cartitem_id')
        action = request.POST.get('action')
        cart_item = get_object_or_404(CartItem, id=cart_item_id, cart__user=request.user)
        product = cart_item.product
        product_quantity = get_quantity_from_api(product.code)

        if action == 'increase':
            increment = Decimal('1.0') if product.unit_type == 1 else Decimal('0.1')
            cart_item.quantity += increment

            if product_quantity < cart_item.quantity:
                messages.error(request, 'تعداد درخواستی از مانده انبار بیشتر می باشد!')
                return redirect(request.META.get('HTTP_REFERER', 'carts:all'))

        elif action == 'decrease':
            increment = Decimal('1.0') if product.unit_type == 1 else Decimal('0.1')
            if cart_item.quantity >= 0.1:
                cart_item.quantity -= increment
                if cart_item.quantity <= 0:
                    cart_item.delete()
                    # messages.error(request, 'تعداد نمیتواند کمتر از 1 باشد!')
                    return redirect(request.META.get('HTTP_REFERER', 'carts:all'))

        cart_item.save()

        # return redirect('carts:all')
        return redirect(request.META.get('HTTP_REFERER', 'carts:all'))

templates/carts/my-carts.html
{% extends 'base.html' %}
{% load static %}


{% block title %} سبد خرید {% endblock %}

{% block style %} 
    <link rel="stylesheet" href="{% static 'styles/jalalidatepicker.min.css' %}" />
    <link href="{% static 'styles/nouislider.css' %}" rel="stylesheet" />
    <script src="{% static 'scripts/nouislider.js' %}"></script>
{% endblock %}

{% block content %}
    
    <main class="lg:pt-[130px]">
    
    
    
        {% if not carts %}
      <section class="my-4">
        <div
          class="container py-10 flex select-none items-center justify-center flex-col md:boxBorder rounded-md gap-5"
        >
          <div class="flex flex-col items-center">
            <img
              class="w-full"
              src="{% static 'assets/images/empty-cart.svg' %}"
              alt="xxx"
            />
            <h1 class="md:text-2xl text-lg">سبد خرید شما خالی است!</h1>
          </div>
          <a
            href="{% url 'products:product_list' %}"
            class="bg-redColor mt-16 border-none opacity-80 hover:opacity-100 transition-opacity duration-300 text-whiteColor px-5 py-2 rounded-md"
            >بازگشت به فروشگاه</a
          >
        </div>
      </section>
        {% else %}
            
            
            
            
      <section
        id="hiddenContent"
        class="bg-lowOpacityColorBg items-start hidden fixed z-[9] top-0 right-0 w-full h-screen"
      ></section>
      <section>
        <div
          class="container flex gap-2 text-lowGray text-[12px] text-nowrap overflow-auto"
        >
          <a href="{% url 'products:home' %}">صفحه اصلی</a>
          <span class="select-none">/</span>
          <p>سبد خرید</p>
        </div>
      </section>
      <section>
        <div class="container text-lowGray px-4 boxBorder rounded-lg mb-5">
        
        
            
            
            
          <div class="boxBorder rounded-lg">
            <table class="lg:table hidden w-full">
              <thead>
                <tr>
                  <th class="text-start px-4 py-4">#</th>
                  <th class="text-start px-4 py-4">
                    <img
                      src="{% static 'assets/images/imageicon.png' %}"
                      class="max-w-[40px]"
                      alt="xxx"
                    />
                  </th>
                  <th class="text-start px-4 py-4">نام محصول</th>
                  <th class="text-start px-4 py-4">تعداد</th>
                  <th class="text-start px-4 py-4">قیمت</th>
                  <th class="text-start px-4 py-4">جمع</th>
                  <th class="text-start px-4 py-4"></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              
              
              {% for cart_item in carts %}
                <tr class="odd:bg-lowerGray">
                  <td class="text-sm px-4">{{ forloop.counter }}</td>
                  <td class="text-sm px-4">
                    <a href="{% url 'products:product_detail' cart_item.product.id %}">
                        
                      <img
                        src="{% if cart_item.product.cover_image %}
                            {{ cart_item.product.cover_image.url }}
                            {% else %}
                            {% static 'assets/images/default-image2.jpg' %}
                            {% endif %}"
                        alt="xxx"
                        class="max-w-[80px] max-y-[100px] aspect-[16/9] object-contain"
                      />
                        
                    </a>
                  </td>
                  <td class="text-sm px-4">{{ cart_item.product.name }}</td>
                  <td class="text-sm px-4">
                      
                      
                  <form method="post" action="{% url 'carts:update_cartitem' %}">
                          {% csrf_token %}
                              <input type="hidden" name="cartitem_id" value="{{ cart_item.id }}">
                    <div
                      class="flex pcsProduct bg-whiteColor justify-between p-2 max-w-[200px] w-full rounded-lg gap-2 boxBorder"
                    >
                      <button type="submit" name="action" value="increase">
                        <i class="text-lg fa fa-plus"></i>
                      </button>
                        <label>
                            <input
                              disabled
                              type="text"
                              class="bg-[transparent] text-center w-full outline-none"
                              name="asd"
                              value="{{ cart_item.rounded_quantity }}"
                            />
                        </label>
                        <button type="submit" name="action" value="decrease">
                        <i class="text-lg fa fa-minus"></i>
                      </button>
                    </div>
                    {% if cart_item.product.unit_type == 1 %}    
                        عدد
                    {% else %}
                        کیلو
                    {% endif %}
                  </form>
                          
                      
                  </td>
                  <td class="text-sm px-4">
                    {{ cart_item.product.discounted_price }}
                    <span>تومان</span>
                  </td>
                  <td class="text-sm px-4">
                    {{ cart_item.cart_item_discounted_price }}
                    <span>تومان</span>
                  </td>
                  <td class="text-sm">
                    <a href="{% url 'carts:remove' cart_item.id %}" class="hover:text-primary"
                      ><i class="fa fa-trash fa-lg"></i
                    ></a>
                  </td>
                </tr>
              {% endfor %}
              
              
              </tbody>
            </table>
          
          
          
          
            <ul class="lg:hidden flex gap-2 flex-col">
                
                {% for cart_item in carts %}
              <li class="p-2 odd:bg-lowerGray flex gap-2 flex-col">
                <div class="flex justify-between items-center py-2">
                  <span>ردیف</span>
                  <span>{{ forloop.counter }}</span>
                </div>
                <div class="flex justify-between items-center py-2">
                  <span>نام محصول</span>
                  <span>{{ cart_item.product.name }}</span>
                </div>
                  
                <div class="flex justify-between items-center py-2">
                  <span>تعداد</span>
                  <div>
                      <form method="post" action="{% url 'carts:update_cartitem' %}">
                      {% csrf_token %}
                              <input type="hidden" name="cartitem_id" value="{{ cart_item.id }}">
                      
                    <div
                      class="pcsProduct bg-whiteColor flex justify-between p-2 max-w-[150px] w-full rounded-lg gap-2 boxBorder"
                    >
                      <button type="submit" name="action" value="increase">
                        <i class="text-lg fa fa-plus"></i>
                      </button>
                        <label>
                            <input
                              disabled
                              type="text"
                              class="bg-[transparent] text-center w-full outline-none"
                              name="asd"
                              value={{ cart_item.rounded_quantity }}
                            />
                        </label>
                        <button type="submit" name="action" value="decrease">
                        <i class="text-lg fa fa-minus"></i>
                      </button>
                    </div>
                    <span class="text-sm text-end w-full block">
                    {% if cart_item.product.unit_type == 1 %}    
                        عدد
                    {% else %}
                        کیلو
                    {% endif %}
                    </span>
                          </form>
                  </div>
                </div>
                  
                  
                  
                <div class="flex justify-between items-center py-2">
                  <span>قیمت</span>
                  <span class="text-sm">
                    {{ cart_item.product.discounted_price }}
                    <span>تومان</span>
                  </span>
                </div>

                <div class="flex justify-between items-center py-2">
                  <span>جمع</span>
                  <span class="text-sm">
                    {{ cart_item.cart_item_discounted_price }}
                    <span>تومان</span>
                  </span>
                </div>

                <div class="flex justify-between items-center py-2">
                  <span></span>
                  <span
                    ><a href="{% url 'carts:remove' cart_item.id %}" class="hover:text-primary"
                      ><i class="fa fa-trash fa-lg"></i></a
                  ></span>
                </div>
              </li>
                {% endfor %}
                
            </ul>
          </div>
        
        
        
        
          <div class="flex justify-end py-2">
            <div class="md:w-1/2 w-full flex flex-col gap-4">
              <h1 class="flex flex-col gap-1">
                جمع کل سبد خرید
                <span
                  class="w-full max-w-[60px] border-[1.5px] border-primary"
                ></span>
              </h1>
              <div class="flex gap-2 flex-col">
{#                <div#}
{#                  class="flex justify-between border-b p-2 border-submitPageColorBorderLowBlack"#}
{#                >#}
{#                  <span>جمع:</span>#}
{#                  <p>#}
{#                    <span></span>#}
{#                    <span>تومان</span>#}
{#                  </p>#}
{#                </div>#}
                <div class="flex justify-between p-2">
                  <span>مبلغ قابل پرداخت:</span>
                  <p>
                    <span>{{ cart.calculate_total_discounted_price }}</span>
                    <span>تومان</span>
                  </p>
                </div>
                <div class="flex justify-between p-2">
                  <span>تعداد کل کالا ها:</span>
                  <p>
                      
                    <span>{{ cart.total_quantity }}</span>
                    <span>عدد</span>
                      
                  </p>
                </div>
                <div class="flex justify-end">
                  <a
                    href="{% url 'orders:checkout' %}"
                    class="py-2 px-3 w-max bg-redColor opacity-75 hover:opacity-100 transition-all text-[16px] text-whiteColor rounded-lg"
                    >ادامه فرآیند خرید</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
        {% endif %}
    </main>
  
  
    
    
    
    
 {% endblock %}






{% block scripts %} 
      <script
      type="text/javascript"
      src="{% static 'scripts/jalalidatepicker.min.js' %}"
    ></script>
    <script src="{% static 'scripts/jquery.js' %}"></script>
    <script src="{% static 'scripts/main.js' %}"></script>
{#    <script>#}
{#      let methodNumber = 0.1;#}
{#      let minLength = methodNumber;#}
{#      let maxFloat = 1;#}
{#      Array.from($(".pcsProduct button")).forEach((btn) => {#}
{#        btn.addEventListener("click", () => {#}
{#          if (btn.children[0].classList.contains("fa-plus")) {#}
{#            let value =#}
{#              Number(btn.nextElementSibling.value) + Number(methodNumber);#}
{#            if (String(value).includes(".")) value = value.toFixed(maxFloat);#}
{#            btn.nextElementSibling.value = value;#}
{#          } else if (btn.previousElementSibling.value > minLength) {#}
{#            let value =#}
{#              Number(btn.previousElementSibling.value) - Number(methodNumber);#}
{#            if (String(value).includes(".")) value = value.toFixed(maxFloat);#}
{#            console.log(btn.previousElementSibling);#}
{#            btn.previousElementSibling.value = value;#}
{#          }#}
{#        });#}
{#      });#}
{##}
{#      $("#pcsProduct button").on("click", function () {});#}
{#    </script>#}
{% endblock %}